# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Memoria.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
import os
import subprocess

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="root",
  database = "memoria"
)

mycursor = mydb.cursor()


dir = os.getcwd()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        title = "Memoria"
        MainWindow.setObjectName("Memoria")
        MainWindow.resize(656, 531)
        MainWindow.setWindowTitle(title)
        MainWindow.setWindowIcon(QtGui.QIcon(dir + "/files/memory.png"))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_gray = QtWidgets.QLabel(self.centralwidget)
        self.label_gray.setEnabled(True)
        self.label_gray.setGeometry(QtCore.QRect(-10, 20, 671, 461))
        self.label_gray.setStyleSheet("background-color : #73726F")
        self.label_gray.setText("")
        self.label_gray.setObjectName("label_gray")
        self.label_black = QtWidgets.QLabel(self.centralwidget)
        self.label_black.setGeometry(QtCore.QRect(0, 0, 661, 61))
        self.label_black.setStyleSheet("background-color : rgb(64, 63, 60)")
        self.label_black.setText("")
        self.label_black.setObjectName("label_black")
        self.label_black_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_black_2.setGeometry(QtCore.QRect(0, 450, 661, 51))
        self.label_black_2.setStyleSheet("background-color : rgb(64, 63, 60)")
        self.label_black_2.setText("")
        self.label_black_2.setObjectName("label_black_2")
        self.UserTextPanel = QtWidgets.QTextEdit(self.centralwidget)
        self.UserTextPanel.setGeometry(QtCore.QRect(380, 10, 260, 32))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(12)
        self.UserTextPanel.setFont(font)
        self.UserTextPanel.setStyleSheet("background-color : #F2F2EB;\n"
"border-radius : 5px\n"
"")
        self.UserTextPanel.setObjectName("UserTextPanel")
        self.SubmitButton = QtWidgets.QPushButton(self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(310, 10, 61, 32))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SubmitButton.setFont(font)
        self.SubmitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SubmitButton.setStyleSheet("QPushButton{\n"
"    background-color : #F2F2EB;\n"
"    border-radius : 7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color : #D9D8D7;\n"
"}\n"
"")
        self.SubmitButton.setObjectName("SubmitButton")
        self.ReloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.ReloadButton.setGeometry(QtCore.QRect(10, 10, 61, 32))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ReloadButton.setFont(font)
        self.ReloadButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ReloadButton.setStyleSheet("QPushButton{\n"
"    background-color : #F2F2EB;\n"
"    border-radius : 7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color : #D9D8D7;\n"
"}\n"
"")
        self.ReloadButton.setObjectName("ReloadButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.SubmitButton.clicked.connect(lambda : self.ChatBot())
        self.ReloadButton.clicked.connect(lambda : self.Reload())
        
        mycursor.execute("TRUNCATE TABLE Files;")
        for path in os.listdir(dir + '/Jeux/'):
                mycursor.execute("INSERT INTO Files (title, dir) VALUES ('"+path+"', '"+dir+"/Jeux/"+path+"')")
                mydb.commit()
                           
        mycursor.execute("SELECT title FROM Files")
        i,j, z = 0,0,0
        self.btn = []
        for x in mycursor:
                title = x[0].split(" ")
                word = ""
                for k in range(len(title)):
                        title[k] = title[k].lower()
                        word += title[k]
                
                self.btn.append(z)
                self.btn[z]= QtWidgets.QPushButton(self.centralwidget)
                self.btn[z].setEnabled(True)
                self.btn[z].setText('{0}'.format(x[0]))
                self.btn[z].setStyleSheet("QPushButton{background-color : #F2F2EB;border-radius : 7px;}QPushButton:pressed{background-color : #D9D8D7;}")
                self.btn[z].setGeometry(QtCore.QRect(10+i*160,80+j*190, 150,150))
                self.btn[z].clicked.connect(lambda checked, a=x[0]: self.Launch(a))
                z += 1                                
                i += 1
                if i == 4:
                        i = 0
                        j += 1 
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Memoria", "Memoria"))
        self.SubmitButton.setText(_translate("MainWindow", "Search"))
        self.ReloadButton.setText(_translate("MainWindow", "Reload"))

    def Launch(self, a):
        launched = False
        os.chdir(dir + '/Jeux/'+a)
        for path2 in os.listdir(dir + '/Jeux/'+a):
                if path2.endswith(".exe") and launched == False:
                        subprocess.Popen(path2)
                        launched = True
        
    def ChatBot(self):
        request = self.UserTextPanel.toPlainText() #get text from user
        word = str(request)
        mycursor.execute("SELECT title FROM files WHERE title = '"+ word +"'")
        myresult = ""
        for x in mycursor:
            myresult += x[0]
        title = x[0].split(" ")
        word2 = ""
        for k in range(len(title)):
                title[k] = title[k].lower()
                word2 += title[k]
                               
        mycursor.execute("SELECT title FROM Files")
        z = 0
        for x in mycursor:
                mot = ""
                for i in range (len(x[0].split(" "))): mot += x[0].split(" ")[i].lower()
                if mot != word2:
                        self.btn[z].hide()
                else:
                        self.btn[z].show()
                        self.btn[z].setGeometry(QtCore.QRect(10, 80, 150, 150))
                z += 1         
                        
    def Reload(self):
        mycursor.execute("TRUNCATE TABLE Files;")
        for path in os.listdir(dir + '/Jeux/'):
                mycursor.execute("INSERT INTO Files (title, dir) VALUES ('"+path+"', '"+dir+"/Jeux/"+path+"')")
                mydb.commit()
                           
        mycursor.execute("SELECT title FROM Files")
        i,j = 0,0
        for x in mycursor:
                title = x[0].split(" ")
                word = ""
                for k in range(len(title)):
                        title[k] = title[k].lower()
                        word += title[k]
                                        
                exec("self.%s = QtWidgets.QPushButton(self.centralwidget)"%word)
                exec("self.%s.setEnabled(True)"%word)
                exec("self.%s.setGeometry(QtCore.QRect(%d, %d, 150, 150))"%(word, 10+i*160, 80+j*190))
                exec("self.%s.setText('%s',"")"%(word,x[0]))
                exec('self.%s.setStyleSheet("QPushButton{background-color : #F2F2EB;border-radius : 7px;}QPushButton:pressed{background-color : #D9D8D7;}")'%word)
                exec("self.%s.setObjectName('SubmitButton')"%(word))
                exec("self.%s.show()"%word)
                exec("self.%s.clicked.connect(lambda : %s)"%(word,"self.ChatBot()"))
                
                i += 1
                if i == 4:
                        i = 0
                        j += 1   
                        
                        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
