# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Memoria.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import nltk
import mysql.connector
import os
import subprocess

mydb = mysql.connector.connect(
  host="localhost",
  user="root",
  password="root",
  database = "memoria"
)

mycursor = mydb.cursor()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_gray = QtWidgets.QLabel(self.centralwidget)
        self.label_gray.setEnabled(True)
        self.label_gray.setGeometry(QtCore.QRect(-10, 20, 671, 461))
        self.label_gray.setStyleSheet("background-color : #73726F")
        self.label_gray.setText("")
        self.label_gray.setObjectName("label_gray")
        self.label_black = QtWidgets.QLabel(self.centralwidget)
        self.label_black.setGeometry(QtCore.QRect(0, 0, 661, 41))
        self.label_black.setStyleSheet("background-color : rgb(64, 63, 60)")
        self.label_black.setText("")
        self.label_black.setObjectName("label_black")
        self.label_black_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_black_2.setGeometry(QtCore.QRect(0, 450, 661, 51))
        self.label_black_2.setStyleSheet("background-color : rgb(64, 63, 60)")
        self.label_black_2.setText("")
        self.label_black_2.setObjectName("label_black_2")
        self.UserTextPanel = QtWidgets.QTextEdit(self.centralwidget)
        self.UserTextPanel.setGeometry(QtCore.QRect(88, 60, 480, 100))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(14)
        self.UserTextPanel.setFont(font)
        self.UserTextPanel.setStyleSheet("background-color : #F2F2EB;\n"
"border-radius : 5px\n"
"")
        self.UserTextPanel.setObjectName("UserTextPanel")
        self.SubmitButton = QtWidgets.QPushButton(self.centralwidget)
        self.SubmitButton.setGeometry(QtCore.QRect(278, 180, 100, 28))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SubmitButton.setFont(font)
        self.SubmitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SubmitButton.setStyleSheet("QPushButton{\n"
"    background-color : #F2F2EB;\n"
"    border-radius : 7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color : #D9D8D7;\n"
"}\n"
"")
        self.SubmitButton.setObjectName("SubmitButton")
        self.AnswerPanel = QtWidgets.QTextEdit(self.centralwidget)
        self.AnswerPanel.setGeometry(QtCore.QRect(88, 300, 480, 100))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(14)
        self.AnswerPanel.setFont(font)
        self.AnswerPanel.setStyleSheet("background-color : #F2F2EB;\n"
"border-radius : 5px\n"
"")
        self.AnswerPanel.setObjectName("AnswerPanel")
        self.AnswerPanel.setReadOnly(True)
        self.AnswerPanel.hide()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.SubmitButton.clicked.connect(lambda : self.ChatBot())
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Memoria"))
        self.SubmitButton.setText(_translate("MainWindow", "Submit"))

    def ChatBot(self):
        self.AnswerPanel.show()
        request = self.UserTextPanel.toPlainText() #get text from user
        word = str(request)
        mycursor.execute("SELECT dir FROM files WHERE title = '"+ word +"'")
        myresult = ""
        for x in mycursor:
            myresult += x[0]
        print(myresult)
        #dir = os.listdir("cd " + myresult+"")
        #print(dir)
        #subprocess.Popen()
        self.AnswerPanel.setText(myresult)
        self.UserTextPanel.setText("")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
